return {
  bind = true,
  doc_lines = 10,
  floating_window = true,
  fix_pos = true,
  hint_enable = true,
  hint_prefix = "🐼 ",
  hint_scheme = "String",
  hi_parameter = "LspSignatureActiveParameter",
  max_height = 12,
  max_width = 80,
  handler_opts = {
    border = "rounded",
  },
  always_trigger = false,
  auto_close_after = nil,
  extra_trigger_chars = {},
  zindex = 200,
  padding = " ",
  transparency = nil,
  shadow_blend = 13,
  shadow_guibg = "Black",
  timer_interval = 200,
  toggle_key = nil,
  select_signature_key = nil,
  move_cursor_key = nil,
}
